name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          cache: gradle
          java-version: 25
      - name: Build
        run: ./gradlew build
      - name: List build output
        run: ls -la worldedit-bukkit/build/libs/
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FastAsyncWorldEdit-Bukkit-SNAPSHOT
          path: worldedit-bukkit/build/libs/FastAsyncWorldEdit-*.jar
